refresh_seconds: 60

rules:
  - label: Verde
    max_minutes: 15
    color: "green"
  - label: Amarelo
    max_minutes: 20
    color: "yellow"
  - label: Vermelho
    max_minutes: null
    color: "red"
